from wspru_api import WspRuAPI
from init_data import INIT_DATA
from gte_r import GTECalcR


wspru_api = WspRuAPI()


class SPECalcR(GTECalcR):

    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)
        self.p1gte = self.piair
        self.T1gte = self.Tiair
        self._check_boiler_temperature()
        self.Q1_cc = self.Q1_spe = self.Q1_gte

    def _check_boiler_temperature(self):
        """Check difference of temperature before boiler and after (not less than 20 oC).
        """
        if self.T4gte - self.Tb_out < 20:
            raise BaseException('Temperature must be more than 20 oC')
        return

    @property
    def pd(self):
        """Steam pressure in boiler drum.
        """
        return self.p4gte + self.deltaps

    @property
    def hb_in(self):
        """-->(in) steam enthalpy of boiler (J/kg of water steam).
        """
        return wspru_api.wspg('HGST', self.gsg, self.T4gte)

    @property
    def hb_out(self):
        """<--(out) steam enthalpy from boiler (J/kg of water steam).
        """
        return wspru_api.wsp('HPT', self.pb_out, self.Tb_out)

    @property
    def Db(self):
        """Steam consumption generated by boiler (kg of water steam / sec).
        """
        return self.Gr * self.hb_in / float(self.hb_out)

    @property
    def pst_in(self):
        """Steam pressure at the inlet of ST (Pa).
        """
        return self.pb_out * (1 - self.sigmapp)

    @property
    def hst_in(self):
        """Steam enthalpy at the inlet of ST (J/kgws).
        """
        return wspru_api.wsp('HPT', self.pst_in, self.Tb_out)

    @property
    def h2spe(self):
        """Steam enthalpy after ST (J/kgws).
        """
        return wspru_api.wsp('HPT', self.p2spe, self.T2spe)

    @property
    def Pst(self):
        """Inner ST power (W).
        """
        return self.Db * (self.hst_in - self.h2spe)

    @property
    def NelSPE(self):
        """Electric power of SPE (W).
        """
        return self.Pst * self.ETAm_spe * self.ETAg_spe

    @property
    def NelCC(self):
        """Electric power of CC (W).
        """
        return self.NelGTE + self.NelSPE

    @property
    def ETAelSPE(self):
        """Electrical efficiency of SPE.
        """
        return self.NelSPE / float(self.Q1_spe)

    @property
    def ETAelCC(self):
        """Electrical efficiency of CC.
        """
        return self.NelCC / float(self.Q1_cc)


if __name__ == '__main__':
    real_calc = SPECalcR(**INIT_DATA)
    # print "ETA gte: %s" % real_calc.ETAelGTE
    # print "ETA spe: %s" % real_calc.ETAelSPE
    # print "ETA cc: %s" % real_calc.ETAelCC
    print "ETA boiler: %s" % real_calc.ETAb
